# Generated by Django 3.0.7 on 2021-11-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20211023_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Команда'},
        ),
    ]
