# Generated by Django 3.0.7 on 2021-11-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20211105_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('Tas', 'Tashkent'), ('Sam', 'Samarkand'), ('Karakalpakstan', 'Karakalpakstan'), ('Urg', 'Urgench'), ('Fer', 'Fergana'), ('And', 'Andijan'), ('Nam', 'Namangan'), ('Gul', 'Gulistan'), ('Jiz', 'Jizzax'), ('Qar', 'Qarshi'), ('Ter', 'Termez'), ('Bux', 'Buxara'), ('Nav', 'Navoi')], max_length=100, verbose_name='Штат'),
        ),
    ]
